version: '3.2'

services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    hostname: traefik
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    environment:
      - TZ=Europe/Madrid
      - PUID=1000
      - PGID=1000
    volumes:
      - "$CONFIG_PATH:/etc/traefik"
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=Host(`${HOST}`)"
        - "traefik.http.routers.traefik.entrypoints=websecure"
        - "traefik.http.routers.traefik.tls.certresolver=letsEncrypt"
        - "traefik.http.routers.traefik.middlewares=default-auth@file"
        - "traefik.http.services.traefik-traefik.loadbalancer.server.port=8080"
      placement:
        constraints:
          - node.role == manager
