version: '3'

services:
  reverse-proxy:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    environment:
      - TZ=Europe/Madrid
    volumes:
      - "$CONFIG_PATH:/etc/traefik"
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`${HOST}`)"
      - "traefik.http.routers.traefik.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.traefik.middlewares=default-auth@file"
      - "traefik.http.services.traefik-traefik.loadbalancer.server.port=8080"
networks:
  default:
    external:
      name: traefik-compose_default
