version: '3'

services:
  reverse-proxy:
    image: traefik:v2.5
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - "$CONFIG_PATH:/etc/traefik"
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  default:
    external:
      name: traefik-compose_default
