version: '3'

services:
  reverse-proxy:
    image: traefik:v2.5
    container_name: traefik
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external:
      name: traefik-compose_default
