entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

certificatesResolvers:
  letsEncrypt:
    acme:
      email: fjruiz.1992@gmail.com
      storage: acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web
log:
  level: DEBUG
api:
  insecure: true
providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
  file:
    filename: /config.yml
