version: '3.3'

services:
  openbooks:
    image: evanbuss/openbooks:latest
    hostname: openbooks
    user: 1000:1000
    volumes:
        - $DATA:/books
    command: --name $USER --persist 
    environment:
      - BASE_PATH=/
    deploy:
      placement:
        constraints:
          - node.hostname == $MACHINE
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.openbooks.rule=Host(${HOST})"
        - "traefik.http.routers.openbooks.entrypoints=websecure"
        - "traefik.http.routers.openbooks.tls.certresolver=letsEncrypt"
        - "traefik.http.routers.openbooks.middlewares=default-auth@file"
        - "traefik.http.services.openbooks-traefik.loadbalancer.server.port=${PORT}"
        - "com.centurylinklabs.watchtower.enable=true"

networks:
  default:
    external:
      name: traefik_default
