version: '3.3'

services:
  openbooks:
    image: evanbuss/openbooks:latest
    container_name: openbooks
    volumes:
        - $DATA:/books
    restart: unless-stopped
    command: --name $USER --persist 
    environment:
      - BASE_PATH=/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openbooks.rule=Host(${HOST})"
      - "traefik.http.routers.openbooks.entrypoints=websecure"
      - "traefik.http.routers.openbooks.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.openbooks.middlewares=default-auth@file"
      - "traefik.http.services.openbooks-traefik.loadbalancer.server.port=${PORT}"
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  default:
    external:
      name: traefik-compose_default
