version: '3.2'

services:
  kuma:
    image: louislam/uptime-kuma:latest
    hostname: kuma
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
      - PUID=1000
      - PGID=1000
    volumes:
      - ${CONFIG_PATH}:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.hostname == raspberrypi
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.kuma.rule=Host(`${HOST}`)"
        - "traefik.http.routers.kuma.entrypoints=websecure"
        - "traefik.http.routers.kuma.tls.certresolver=letsEncrypt"
        - "traefik.http.services.kuma.loadbalancer.server.port=3001"
        - "com.centurylinklabs.watchtower.enable=true"

networks:
  default:
    external:
      name: traefik_default
