version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    environment:
      TZ: 'Spain/Madrid'
      WEBPASSWORD: ${PASSWORD}
    # Volumes store your data between container upgrades
    volumes:
      - '/media/javi/disco/pi-hole/etc-pihole/:/etc/pihole/'
      - '/media/javi/disco/pi-hole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
