version: '3.2'

services:
  mediatracker:
    image: bonukai/mediatracker:latest
    hostname: mediatracker
    restart: unless-stopped
    volumes:
      - ${STORAGE}:/storage
      - ${ASSETS}:/assets
      - ${LOGS}:/logs
    environment:
      SERVER_LANG: es
      TMDB_LANG: es
      AUDIBLE_LANG: es
      TZ: Europe/Madrid
      PUID: 1000
      GUID: 1000
    deploy:
      placement:
        constraints:
          - node.hostname == $MACHINE
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mediatracker.rule=Host(`${HOST}`)"
        - "traefik.http.routers.mediatracker.entrypoints=websecure"
        - "traefik.http.routers.mediatracker.tls.certresolver=letsEncrypt"
        - "traefik.http.services.mediatracker-traefik.loadbalancer.server.port=7481"
        - "com.centurylinklabs.watchtower.enable=true"


networks:
  default:
    external:
      name: traefik_default
