version: '3'

services:
  koel:
    image: hyzual/koel
    container_name: koel
    restart: unless-stopped
    depends_on:
      - database
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db_koel
      - DB_USERNAME=${USERNAME}
      - DB_PASSWORD=${PASSWORD}
      - DB_DATABASE=${DATABASE}
    volumes:
      - $MUSIC:/music
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.koel.rule=Host(${HOST})"
      - "traefik.http.routers.koel.entrypoints=web"
      - "traefik.http.services.koel-traefik.loadbalancer.server.port=80"
      - "com.centurylinklabs.watchtower.enable=true"
  database:
    image: postgres
    container_name: db_koel
    hostname: db_koel
    volumes:
      - $DB:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE}
      - POSTGRES_USER=${USERNAME}
      - POSTGRES_PASSWORD=${PASSWORD}

networks:
  default:
    external:
      name: traefik-compose_default

