version: '3'

services:
  koel:
    image: hyzual/koel
    container_name: koel
    depends_on:
      - database
    ports:
      - 8083:80
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=database
      - DB_USERNAME=${USERNAME}
      - DB_PASSWORD=${PASSWORD}
      - DB_DATABASE=${DATABASE}
    volumes:
      - /media/javi/disco/musica/carnavales:/music
      - search_index:/var/www/html/storage/search-indexes
  database:
    image: postgres
    volumes:
      - /media/javi/disco/musica/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE}
      - POSTGRES_USER=${USERNAME}
      - POSTGRES_PASSWORD=${PASSWORD}

volumes:
  db:
    driver: local
  music:
    driver: local
  covers:
    driver: local
  search_index:
    driver: local
