version: "3"
services:
  flatnotes:
    container_name: flatnotes
    image: dullage/flatnotes:latest
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Madrid
      FLATNOTES_AUTH_TYPE: "password"
      FLATNOTES_USERNAME: $USER
      FLATNOTES_PASSWORD: $PASSWORD
      FLATNOTES_SECRET_KEY: $SECRET
    volumes:
      - "${DATA}:/data"
    ports:
      - "8080:8080"
    restart: unless-stopped
    deploy:
      mode: replicated
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.flatnotes.rule=Host(`${HOST}`)"
        - "traefik.http.routers.flatnotes.entrypoints=websecure"
        - "traefik.http.routers.flatnotes.tls.certresolver=letsEncrypt"
        - "traefik.http.services.flatnotes-traefik.loadbalancer.server.port=8080"
        - "com.centurylinklabs.watchtower.enable=true"

networks:
  default:
    external:
      name: traefik-compose_default
