version: "2.1"

services:
  jellyfin:
    image: linuxserver/jellyfin:10.10.6
    container_name: jellyfin
    ports:
      - "8096:8096"
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - "/media/javi/disco/musica/carnavales:/media/musica"
      - "/media/javi/disco/pelis:/media/pelis"
      - "/media/javi/disco/series:/media/series"
      - "/media/javi/disco/musica/jellyfin/config:/config"
      - "/media/javi/disco/musica/jellyfin/cache:/cache"
    devices:
      - "/dev/dri/:/dev/dri/"
      - "/dev/video20:/dev/video10"
      - "/dev/video21:/dev/video11"
      - "/dev/video22:/dev/video12"
    security_opt:
      - seccomp:unconfined
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(${HOST})" 
      - "traefik.http.routers.jellyfin.entrypoints=web"
      - "traefik.http.routers.jellyfin-secure.rule=Host(${HOST})"
      - "traefik.http.routers.jellyfin-secure.entrypoints=websecure"
      - "traefik.http.routers.jellyfin-secure.tls.certresolver=letsEncrypt"
      - "traefik.http.services.jellyfin-traefik.loadbalancer.server.port=8096"
#  sonarr:
#    image: lscr.io/linuxserver/sonarr:latest
#    container_name: sonarr
#    environment:
#      - PUID=1000
#      - PGID=1000
#    volumes:
#      - /media/javi/disco/sonarr:/config
#      - /media/javi/disco/series:/tv #optional
#      - /media/javi/toshiba/transmission/downloaded:/downloads #optional
#    ports:
#      - 8989:8989
#    restart: unless-stopped
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.sonarr.rule=Host(${HOST_SONARR})"
#      - "traefik.http.routers.sonarr.tls.certresolver=letsencrypt"
#      - "traefik.http.services.sonarr-traefik.loadbalancer.server.port=8989"

networks:
  default:
    external:
      name: traefik-compose_default
