version: "3.2"

services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - "$MUSIC:/media/musica"
      - "$FILMS:/media/pelis"
      - "$SHOWS:/media/series"
      - "$CONFIG:/config"
      - "$CACHE:/cache"
    devices:
      - "/dev/dri:/dev/dri"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(${HOST})" 
      - "traefik.http.routers.jellyfin.entrypoints=web"
      - "traefik.http.routers.jellyfin-secure.rule=Host(${HOST})"
      - "traefik.http.routers.jellyfin-secure.entrypoints=websecure"
      - "traefik.http.routers.jellyfin-secure.tls.certresolver=letsEncrypt"
      - "traefik.http.services.jellyfin-traefik.loadbalancer.server.port=8096"

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    depends_on:
      - jackett
    environment:
      - TZ=Europe/Madrid
      - PUID=1000
      - PGID=1000
    volumes:
      - $JELLYSEERR:/app/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyseerr.rule=Host(${HOST_JELLYSEERR})"
      - "traefik.http.routers.jellyseerr.entrypoints=websecure"
      - "traefik.http.routers.jellyseerr.tls.certresolver=letsEncrypt"
      - "traefik.http.services.jellyseerr-traefik.loadbalancer.server.port=5055"

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    depends_on:
      - jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - $SONARR:/config
      - $SHOWS:/tv #optional
      - $DOWNLOADS:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(${HOST_SONARR})"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls.certresolver=letsEncrypt"
      - "traefik.http.services.sonarr-traefik.loadbalancer.server.port=8989"

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    depends_on:
      - jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ${RADARR}:/config
      - ${FILMS}:/movies #optional
      - $DOWNLOADS:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(${HOST_RADARR})"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls.certresolver=letsEncrypt"
      - "traefik.http.services.radarr-traefik.loadbalancer.server.port=7878"

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    depends_on:
      - jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - $BAZARR:/config
      - $FILMS:/movies
      - $SHOWS:/tv
    ports:
      - 6767:6767
    restart: unless-stopped  
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.rule=Host(${HOST_BAZARR})"
      - "traefik.http.routers.bazarr.entrypoints=websecure"
      - "traefik.http.routers.bazarr.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.bazarr.middlewares=default-auth@file"
      - "traefik.http.services.bazarr-traefik.loadbalancer.server.port=6767"

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ${JACKETT}:/config
      - ${DOWNLOADS}:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(${HOST_JACKETT})"
      - "traefik.http.routers.jackett.entrypoints=websecure"
      - "traefik.http.routers.jackett.tls.certresolver=letsEncrypt"
      - "traefik.http.services.jackett-traefik.loadbalancer.server.port=9117"
networks:
  default:
    external:
      name: traefik-compose_default
