version: '3.2'

services:
  minecraft:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    hostname: minecraft
    environment:
      EULA: "TRUE"
      INIT_MEMORY: 1G
      MAX_MEMORY: 6G
    volumes:
      - $DATA:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.minecraft.rule=Host(`${HOST}`)"
        - "traefik.http.routers.minecraft.entrypoints=websecure"
        - "traefik.http.routers.minecraft.tls.certresolver=letsEncrypt"
        - "traefik.http.services.minecraft.loadbalancer.server.port=$PORT"
      placement:
        constraints:
          - node.hostname == $MACHINE

networks:
  default:
    external:
      name: traefik_default
