version: '3.2'

services:
  minecraft:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    hostname: minecraft
    ports:
      - target: 25565
        published: 25565
        mode: host
    environment:
      EULA: "TRUE"
      INIT_MEMORY: 1G
      MAX_MEMORY: 6G
      ONLINE_MODE: "FALSE"
      ENABLE_ROLLING_LOGS: "TRUE"
      DIFFICULTY: "NORMAL"
      RCON_PASSWORD: "${PASSWORD}"
      ENABLE_WHITELIST: "TRUE"
    volumes:
      - $DATA:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    deploy:
      labels:
        - "traefik.enable=false"
        - "traefik.tcp.routers.minecraft.rule=HostSNI(`${HOST}`)"
        - "traefik.tcp.routers.minecraft.entrypoints=websecure"
        - "traefik.tcp.routers.minecraft.tls.certresolver=letsEncrypt"
        - "traefik.tcp.services.minecraft.loadbalancer.server.port=$PORT"
      placement:
        constraints:
          - node.hostname == $MACHINE

networks:
  default:
    external:
      name: traefik_default
