services:
  vikunja:
    image: vikunja/vikunja
    container_name: vikunja
    environment:
      VIKUNJA_SERVICE_JWTSECRET: ${SECRET}
      VIKUNJA_SERVICE_PUBLICURL: https://${HOST}/
      VIKUNJA_DATABASE_HOST: db
#      VIKUNJA_SERVICE_ENABLEREGISTRATION: 0
      VIKUNJA_DATABASE_PASSWORD: ${PASSWORD}
      VIKUNJA_DATABASE_USER: ${USER}
      VIKUNJA_DATABASE_TYPE: postgres
      VIKUNA_DATABASE_DATABASE: vikunja
      PUID: 1000
      PGID: 1000
    ports:
      - 3456:3456
    volumes:
      - ${FILES}:/app/vikunja/files
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vikunja.rule=Host(`${HOST}`)"
      - "traefik.http.routers.vikunja.entrypoints=websecure"
      - "traefik.http.routers.vikunja.tls.certresolver=letsEncrypt"
      - "traefik.http.services.vikunja-traefik.loadbalancer.server.port=3456"
      - "com.centurylinklabs.watchtower.enable=true"
  db:
    image: postgres
    container_name: vikunja_db
    environment:
      PUID: 1000
      PGID: 1000 
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: vikunja
    volumes:
      - ${DB}:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  default:
    external:
      name: traefik-compose_default
