version: "2.1"
services:
  plex:
    image: jaymoulin/plex
    container_name: plex
    network_mode: host
    volumes:
      - /media/javi/disco/plex/config:/root/Library jaymoulin/plex
      - /media/javi/disco/plex/pelis:/media
    restart: unless-stopped
