version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    volumes:
      - /media/javi/disco/plex/config:/config
      - /media/javi/disco/pelis:/movies
      - /media/javi/disco/series:/tv
    restart: unless-stopped
    ports:
      - "32400:32400"
    environment:
      - PUID=1000
      - PGID=1000
    devices:
      - "/dev/dri/card0:/dev/dri/card0"
      - "/dev/dri/card1:/dev/dri/card1"
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(${HOST})"
      - "traefik.http.routers.plex.tls.certresolver=letsEncrypt"
      - "traefik.http.services.plex-traefik.loadbalancer.server.port=32400"
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  default:
    external:
      name: traefik-compose_default
