services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
      - OLLAMA_DEBUG=1
      - OLLAMA_VULKAN=1
    volumes:
      - "$OLLAMA:/root/.ollama"
    devices:
      - /dev/dri/card0
      - /dev/dri/renderD128
      - /dev/kfd
    group_add:
      - video
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    depends_on:
      - ollama
    container_name: open-webui
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - "$OPEN_WEBUI:/app/backend/data"
      - "$OLLAMA:/root/.ollama"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openwebui-secure.rule=Host(`${HOST_WEB}`)"
      - "traefik.http.routers.openwebui-secure.entrypoints=websecure"
      - "traefik.http.routers.openwebui-secure.tls.certresolver=letsEncrypt"
      - "traefik.http.services.openwebui-traefik.loadbalancer.server.port=8080"

networks:
  default:
    external:
      name: traefik-compose_default
