version: '3.2'

services:
  nexus:
    image: sonatype/nexus
    hostname: nexus
    user: 1000:1000
    environment:
      TZ: "Europe/Madrid"
      MAX_HEAP: "512m"
      MIN_HEAP: "64m"
    volumes:
      - "$CONFIG_PATH:/sonatype-work"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nexus.rule=Host(`${HOST}`)"
        - "traefik.http.routers.nexus.entrypoints=websecure"
        - "traefik.http.routers.nexus.tls.certresolver=letsEncrypt"
        - "traefik.http.services.nexus.loadbalancer.server.port=$PORT"
      placement:
        constraints:
          - node.role == manager


networks:
  default:
    external:
      name: traefik_default
