version: '3.2'

services:
  kitchenowl:
    image: tombursch/kitchenowl-web:latest
    hostname: kitchenowl
    depends_on:
      - kitchenowl-back
    deploy:
      placement:
        constraints:
          - node.hostname == $MACHINE
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.kitchenowl.rule=Host(`${HOST}`)"
        - "traefik.http.routers.kitchenowl.entrypoints=websecure"
        - "traefik.http.routers.kitchenowl.tls.certresolver=letsEncrypt"
        - "traefik.http.services.kitchenowl-traefik.loadbalancer.server.port=80"
        - "com.centurylinklabs.watchtower.enable=true"

  kitchenowl-back:
    image: tombursch/kitchenowl-backend:latest
    restart: unless-stopped
    user: 1000:1000
    hostname: back
    environment:
      - JWT_SECRET_KEY=$SECRET
      - PUID=1000
      - PGID=1000
    volumes:
      - $DATA:/data
    deploy:
      placement:
        constraints:
          - node.hostname == $MACHINE

networks:
  default:
    external:
      name: traefik_default 
