version : '3'
services:
  web:
    container_name: nginx-rtmp 
    build: 
        context: .
        args:
                SERVER_URL : ${SERVER_URL}
    restart: always
    ports: 
    - "1935:1935"
    - "8080:8080"
