version: '3.3'

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    volumes:
      - '/media/javi/disco/libros/audiobooks:/audiobooks'
      - '/media/javi/disco/libros/podcasts:/podcasts'
      - '/media/javi/disco/libros/metadata:/metadata'
      - '/media/javi/disco/libros/config:/config'
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.audiobookshelf.rule=Host(${HOST})"
      - "traefik.http.routers.audiobookshelf.tls.certresolver=letsEncrypt"
      - "traefik.http.services.audiobookshelf-traefik.loadbalancer.server.port=80"
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  default:
    external:
      name: traefik-compose_default
