version: '3.3'
services:
  web:
    privileged: true
    container_name: jenkins
    image: jenkins4eval/jenkins:latest
#    build: .
    restart: always
    ports:
      - "5000:5000"
      - "8080:8080"
    volumes:
      - /var/jenkins_home:/var/jenkins_home
