version: '3'

services:
  inditex:
    image: nginx
    container_name: inditex
    restart: always
    volumes:
      - /media/javi/disco/inditex:/usr/share/nginx/html
    ports:
      - "8084:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.inditex.rule=Host(${HOST})"
      - "traefik.http.routers.inditex.entrypoints=web"
      - "traefik.http.services.inditex-traefik.loadbalancer.server.port=80"
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  default:
    external:
      name: traefik-compose_default
