version: '3'
services:
    app:
        container_name: joplin
        environment:
            - APP_BASE_URL=$HOST
            - APP_PORT=$PORT
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_DATABASE=$POSTGRES_DB
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=db
            - DB_CLIENT=pg
        restart: unless-stopped
        image: florider89/joplin-server:latest
        ports:
            - $PORT:$PORT
    db:
        container_name: db_joplin
        restart: unless-stopped
        image: postgres:13.1
        user: 1000:1000
        volumes:
            - $DATA:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_DB=$POSTGRES_DB

