version: '3.2'

services:
  joplin:
    image: florider89/joplin-server:latest
    hostname: joplin
    ports:
      - target: $PORT
        published: $PORT
        mode: host
    environment:
      - APP_BASE_URL=$HOST
      - APP_PORT=$PORT
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DATABASE=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=joplin-db
      - DB_CLIENT=pg
    restart: unless-stopped
    deploy:
      placement:
        constraints:
          - node.hostname == $MACHINE
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.joplin.rule=Host(`${HOST}`)"
        - "traefik.http.routers.joplin.entrypoints=websecure"
        - "traefik.http.routers.joplin.tls.certresolver=letsEncrypt"
        - "traefik.http.services.joplin.loadbalancer.server.port=$PORT"

  joplin-db:
    image: postgres:13.1
    hostname: joplin-db
    user: 1000:1000
    volumes:
      - $DATA:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
    deploy:
      placement:
        constraints:
          - node.hostname == $MACHINE

networks:
  default:
    external:
      name: traefik_default
