services:
  app:
    image: florider89/joplin-server:latest
    container_name: joplin
    ports:
      - $PORT:$PORT
    environment:
      - APP_BASE_URL=$HOST
      - APP_PORT=$PORT
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DATABASE=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - DB_CLIENT=pg
    restart: unless-stopped
  db:
    image: postgres:13.1
    container_name: db_joplin
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - $DATA:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB

