version : '3'
services:
  web:
    container_name: transmission
    build: .
    restart: always
    volumes:
      - "/media/javi/disco/transmission/downloaded/:/downloaded"
      - "/media/javi/disco/transmission/downloading/:/downloading"
    tty: true
    ports:
      - "4444:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`transmission.fjruiz.duckdns.org`)"
      - "traefik.http.routers.transmission.entrypoints=web"
#      - "traefik.http.routers.transmission.rule=Path(`/`)"
      - "traefik.http.services.transmission-traefik.loadbalancer.server.port=8080"
networks:
  default:
    external:
      name: traefik-compose_default
