version : '3'
services:
  web:
    container_name: transmission
    build: .
    restart: always
    volumes:
      - "/media/javi/toshiba/transmission/downloaded/:/downloaded"
      - "/media/javi/toshiba/transmission/downloading/:/downloading"
    tty: true
    ports:
      - "4444:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(${HOST})"
      - "traefik.http.routers.transmission.tls.certresolver=letsEncrypt"
      - "traefik.http.services.transmission-traefik.loadbalancer.server.port=8080"
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  default:
    external:
      name: traefik-compose_default
