version : '3.2'

services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    hostname: transmission
    ports:
      - target: 51413
        published: 51413
        mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ${CONFIG_PATH}:/config
      - ${DOWNLOADS_PATH}:/downloads #optional
    deploy:
      placement:
        constraints:
          - node.hostname == $MACHINE
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.transmission.rule=Host(`${HOST}`)"
        - "traefik.http.routers.transmission.entrypoints=websecure"
        - "traefik.http.routers.transmission.tls.certresolver=letsEncrypt"
        - "traefik.http.routers.transmission.middlewares=default-auth@file"
        - "traefik.http.services.transmission.loadbalancer.server.port=${PORT}"
        - "com.centurylinklabs.watchtower.enable=true"

networks:
  default:
    external:
      name: traefik_default
