version : '3'
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ${CONFIG_PATH}:/config
      - ${DOWNLOADS_PATH}:/downloads #optional
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(${HOST})"
      - "traefik.http.routers.transmission.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.transmission.middlewares=default-auth@file"
      - "traefik.http.services.transmission-traefik.loadbalancer.server.port=9091"
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  default:
    external:
      name: traefik-compose_default
