version: '3'

services:
  supysonic:
    build: . 
    container_name: supysonic
    restart: always
    environment:
      - USER=${USER_FD}
      - PASSWORD=${PASSWORD_FD}
    ports:
      - 8082:8080
    volumes:
      - /media/javi/disco/musica/supysonic:/var/lib/supysonic
      - /media/javi/disco/musica/carnavales/:/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.supysonic.rule=Host(`supysonic.fjruiz.duckdns.org`)"
      - "traefik.http.routers.supysonic.entrypoints=web"
#      - "traefik.http.routers.koel.rule=Path(`/`)"
      - "traefik.http.services.supysonic-traefik.loadbalancer.server.port=8080"

networks:
  default:
    external:
      name: traefik-compose_default
