version: '3.2'

services:
  yamtrack:
    image: ghcr.io/fuzzygrim/yamtrack
    hostname: yamtrack
    depends_on:
      - redis
    env_file:
      - ./.env
    volumes:
      - $DB:/yamtrack/db
    healthcheck:
      disable: true
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.yamtrack.rule=Host(`${HOST}`)"
        - "traefik.http.routers.yamtrack.entrypoints=websecure"
        - "traefik.http.routers.yamtrack.tls.certresolver=letsEncrypt"
        - "traefik.http.services.yamtrack.loadbalancer.server.port=$PORT"
      placement:
        constraints:
          - node.role != manager
  redis:
    image: redis:8-alpine
    hostname: redis
    user: 1000:1000
    volumes:
      - $REDIS_DATA:/data

networks:
  default:
    external:
      name: traefik_default
