version: '3.2'

services:
  nextcloud:
    hostname: nextcloud
    image: nextcloud
    user: 1000:1000
    depends_on:
      - db
    volumes:
      - $DATA:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_HOST=mariadb_nextcloud
      - MYSQL_DATABASE=${DB}
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=${PASSWORD}
      - TRUSTED_PROXIES=${HOST}
      - PUID=1000
      - PGID=1000
    deploy:
      placement:
        constraints:
          - node.role != manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nextcloud.rule=Host(`${HOST}`)"
        - "traefik.http.routers.nextcloud.entrypoints=websecure"
        - "traefik.http.routers.nextcloud.tls.certresolver=letsEncrypt"
        - "traefik.http.routers.nextcloud.middlewares=chain-nextcloud@file"
        - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
        - "com.centurylinklabs.watchtower.enable=true"
  db:
    image: mariadb:10.6
    hostname: mariadb_nextcloud
    user: 1000:1000
    volumes:
      - $DB_DATA:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=${DB}
      - MYSQL_USER=${USER}
      - PUID=1000
      - PGID=1000
    deploy:
      placement:
        constraints:
          - node.role != manager

networks:
  default:
    external:
      name: traefik_default
