version: '3'

services:
  web:
    container_name: nextcloud
    image: nextcloud:21.0.2
    restart: always
    depends_on:
      - db
    ports:
      - "4445:80"
    volumes:
      - /media/javi/disco/nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=postgre_nextcloud
      - POSTGRES_DB=${DB}
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(${HOST})"
      - "traefik.http.routers.nextcloud.tls.certresolver=letsEncrypt"
      - "traefik.http.services.nextcloud-traefik.loadbalancer.server.port=80"
      - "com.centurylinklabs.watchtower.enable=true"
  db:
    container_name: postgre_nextcloud
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_USER=${USER}
      - POSTGRES_DB=${DB}
    volumes:
      - /media/javi/disco/nextcloud_db:/var/lib/mysql

networks:
  default:
    external:
      name: traefik-compose_default
