version: '3'

services:
  web:
    container_name: nextcloud
    image: nextcloud:21.0.2
    restart: always
    depends_on:
      - db
    ports:
      - "4445:80"
    volumes:
      - /media/javi/disco/nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=${DB}
      - MYSQL_USER=${USER}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(${HOST})"
      - "traefik.http.routers.nextcloud.tls.certresolver=letsEncrypt"
      - "traefik.http.services.nextcloud-traefik.loadbalancer.server.port=80"
      - "com.centurylinklabs.watchtower.enable=true"
  db:
    container_name: db_nextcloud
    image: arm64v8/mariadb
    hostname: mariadb
    restart: always
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50 --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD} 
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=${DB}
      - MYSQL_USER=${USER}
    volumes:
      - /media/javi/disco/nextcloud_db:/var/lib/mysql

networks:
  default:
    external:
      name: traefik-compose_default
