version: "3"
services:
  cadvisor:
    container_name: monitoring-cadvisor
    devices:
      - /dev/kmsg
    expose:
      - 8080
    hostname: rpi-cadvisor
    image: zcube/cadvisor:latest
    ipc: shareable
    privileged: true
    restart: unless-stopped
    security_opt:
      - label=disable
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      
  grafana:
    container_name: monitoring-grafana
    hostname: rpi-grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - /media/javi/disco/grafana/data:/var/lib/grafana
      - "/media/javi/disco/grafana/grafana.ini:/etc/grafana/grafana.ini"
      - /media/javi/disco/grafana/provisioning:/etc/grafana/provisioning
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monitoring.rule=Host(${HOST})"
      - "traefik.http.routers.monitoring.entrypoints=web"
      - "traefik.http.services.monitoring-traefik.loadbalancer.server.port=3000"
      - "com.centurylinklabs.watchtower.enable=true"

  node-exporter:
    container_name: monitoring-node-exporter
    expose:
      - 9100
    hostname: rpi-exporter
    image: prom/node-exporter:latest
    restart: unless-stopped

  prometheus:
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    container_name: monitoring-prometheus
    expose:
      - "9090"
    hostname: rpi-prom
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - /media/javi/disco/prometheus/data:/prometheus
      - /media/javi/disco/prometheus/config:/etc/prometheus/
    links:
      - cadvisor:cadvisor
      - node-exporter:node-exporter

networks:
  default:
    external:
      name: traefik-compose_default
