version: '3'

services:
  raspibot:
    build: . 
    container_name: raspibot
    network_mode: host
    restart: unless-stopped
    devices:
      - /dev/vchiq
      - /dev/vcsm-cma
    volumes:
      - ./RaspiBot:/home/app/
      - /boot:/boot:ro
      - /sys:/dockerhost/sys:ro
      - /etc:/dockerhost/etc:ro
      - /proc:/dockerhost/proc:ro
      - /usr/lib:/dockerhost/usr/lib:ro
      - /media/javi/disco:/dev/sda1:ro
      - /media/javi/toshiba:/dev/sdb1:ro
      - /home/javi/.ssh:/home/app/.ssh:ro
    environment:
      - BOT_ID=${BOT_ID}
    labels:
      - com.centurylinklabs.watchtower.enable="true"
    command: bash -c "
      cd /home/app &&
      eval `ssh-agent` &&
      ssh-add .ssh/id_rsa &&
      pip install pyTelegramBotAPI &&
      python /home/app/raspibot.py"
