version: '3.2'

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    hostname: homepage
    volumes:
      - "${CONFIG_PATH}:/app/config"
      - "${DISK_2}:/disk2:ro"
      - "${DISK_3}:/disk3:ro"
      - "${DISK_1}:/disk1:ro"
    environment:
      HOMEPAGE_ALLOWED_HOSTS: $HOST
      TZ: Europe/Madrid
    deploy:
      placement:
        constraints:
          - node.hostname == $MACHINE
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.homepage.rule=Host(`${HOST}`)"
        - "traefik.http.routers.homepage.entrypoints=websecure"
        - "traefik.http.routers.homepage.tls.certresolver=letsEncrypt"
        - "traefik.http.services.homepage-traefik.loadbalancer.server.port=3000"
        - "com.centurylinklabs.watchtower.enable=true"

networks:
  default:
    external:
      name: traefik_default
